#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Running checks before committing...';

# Check Prettier standards
npm run check-format ||
(
    echo 'Formatting check failed';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
    echo 'ESLint check failed';
    false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Type check failed';
    false;
)

# If everything passes... Now we can commit
echo 'Initial checks passed - attempting to build project...';

npm run build ||
(
    echo 'Build failed';
    false;
)

# If everything passes... Now we can commit
echo 'All checks passed!';